package com.softwood.mcp

import com.softwood.mcp.service.ToolHandler
import groovy.json.JsonSlurper
import groovy.transform.CompileDynamic
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import spock.lang.Specification

/**
 * FS 0.9.17 -- the MCPB manifest must declare exactly the tools the server registers.
 *
 * <p><b>RED on 0.9.16, deliberately.</b> The installed manifest declares FOUR tools --
 * {@code file_read, file_write, file_search, server_lifecycle} -- while the server registers
 * EIGHT. {@code file_list}, {@code file_lifecycle}, {@code execute} and {@code tools} were added
 * to the server and never to the manifest, because {@code generateMcpbManifest} in build.gradle
 * held the list as a hand-written literal.
 *
 * <p>Spotted 2026-09-04 from the Claude Desktop extensions panel, which renders the manifest
 * faithfully: four chips for a server that serves eight tools. The installed file was stamped
 * 2026-09-03 08:52, so it HAD been regenerated by that day's build and still said four -- a
 * literal cannot go stale loudly.
 *
 * <p>Functionally the runtime announcement wins ({@code execute} is absent from the manifest and
 * works), so this was never an outage. It is the other thing: <b>a claim in a document everybody
 * reads that nothing measures.</b> The manifest is what the desktop shows a human deciding whether
 * to trust an extension, and it was understating the server's reach by half.
 *
 * <p>The fix derives the manifest from the registered set rather than restating it. This spec is
 * the check that the derivation actually held, and it is deliberately NOT circular: the left-hand
 * side is the manifest as Gradle produced it, and the right-hand side is the live Spring context's
 * {@code List<ToolHandler>} -- the same collection {@code McpController} dispatches against. Two
 * independent paths to one fact.
 *
 * @since FS 0.9.17
 */
@SpringBootTest
@CompileDynamic
class McpbManifestToolCoverageSpec extends Specification {

    /** The registered tool set, by definition: what McpController is handed and dispatches on. */
    @Autowired
    List<ToolHandler> toolHandlers

    private Set<String> registeredToolNames() {
        return toolHandlers.collectMany { ToolHandler h ->
            h.toolDefinitions.collect { Map toolDef -> toolDef.name as String }
        } as Set<String>
    }

    /**
     * Reads the manifest Gradle actually wrote. Prefers the staging copy from the last package
     * run; falls back to the generator's declared list in build.gradle so the spec still means
     * something on a clean checkout that has never packaged.
     */
    private Set<String> declaredToolNames() {
        File staged = new File('build/mcpb-staging/manifest.json')
        if (staged.exists()) {
            def manifest = new JsonSlurper().parse(staged)
            return (manifest.tools ?: []).collect { it.name as String } as Set<String>
        }
        File gradleFile = new File('build.gradle')
        assert gradleFile.exists(), 'neither build/mcpb-staging/manifest.json nor build.gradle found'
        return (gradleFile.text =~ /name\s*:\s*'([a-z_]+)'/)
            .collect { it[1] as String }
            .findAll { it in registeredToolNames() || it.startsWith('file_') || it in ['execute', 'tools', 'server_lifecycle'] } as Set<String>
    }

    def "the MCPB manifest declares every tool the server registers"() {
        given:
        Set<String> registered = registeredToolNames()
        Set<String> declared = declaredToolNames()

        expect: 'the server registers more than the four the literal used to name'
        registered.size() >= 8

        when:
        List<String> undeclared = (registered - declared).toList().sort()

        then:
        assert undeclared.isEmpty(),
            "${undeclared.size()} registered tool(s) are missing from the MCPB manifest, so the " +
            "extensions panel understates what this server does: ${undeclared}"
        true
    }

    def "the MCPB manifest does not advertise tools the server does not register"() {
        given:
        Set<String> registered = registeredToolNames()
        Set<String> declared = declaredToolNames()

        when:
        List<String> phantom = (declared - registered).toList().sort()

        then: 'a manifest naming a tool that does not exist is the same defect pointing the other way'
        assert phantom.isEmpty(),
            "manifest advertises ${phantom.size()} tool(s) the server does not register: ${phantom}"
        true
    }
}
