package com.softwood.mcp.service

import groovy.transform.CompileStatic
import groovy.util.logging.Slf4j
import org.codehaus.groovy.ast.*
import org.codehaus.groovy.ast.expr.ClosureExpression
import org.codehaus.groovy.ast.stmt.BlockStatement
import org.codehaus.groovy.control.CompilationUnit
import org.codehaus.groovy.control.CompilerConfiguration
import org.codehaus.groovy.control.Phases
import org.codehaus.groovy.control.SourceUnit
import org.springframework.stereotype.Component

import java.util.regex.Pattern

/**
 * AstStructureScanner - produces a structure outline for Groovy and Java files.
 *
 * For .groovy files: uses the Groovy AST (CompilationUnit) for accurate parsing -
 *   handles def methods, closures-as-fields, inner classes, traits, scripts.
 *
 * For .java files: falls back to the streaming regex scanner (ChatGPT approach),
 *   which is good enough for 90%+ of standard Java.
 *
 * Returns List<Map> with entries: [line, endLine, type, content, owner?]
 *   type = 'class' | 'interface' | 'enum' | 'trait' | 'method' | 'field' | 'ctor'
 *
 * v1.0.0 - initial
 */
@Component
@Slf4j
@CompileStatic
class AstStructureScanner {

    // FIX-13: shared static instance - CompilerConfiguration is read-only after init, safe to share across threads
    private static final CompilerConfiguration SHARED_COMPILER_CONFIG = new CompilerConfiguration().tap {
        setTolerance(10) // allow some errors - we want partial results
    }

    // -----------------------------------------------------------------------
    // Public API
    // -----------------------------------------------------------------------

    /**
     * Scan a file and return its structure.
     * @param file  the source file
     * @return map with keys: ext (String), structure (List<Map>), scanner ('ast'|'regex'|'none')
     */
    Map<String, Object> scan(File file) {
        String ext = fileExt(file)
        if (ext == 'groovy') {
            try {
                List<Map<String, Object>> structure = scanGroovyAst(file)
                return [ext: ext, structure: structure, scanner: 'ast'] as Map<String, Object>
            } catch (Exception e) {
                log.warn("AST scan failed for ${file.name}, falling back to regex: ${e.message}")
                // Fall through to regex
            }
        }
        if (ext in ['groovy', 'java', 'kt', 'kts']) {
            List<Map<String, Object>> structure = scanRegex(file)
            return [ext: ext, structure: structure, scanner: 'regex'] as Map<String, Object>
        }
        return [ext: ext, structure: [], scanner: 'none'] as Map<String, Object>
    }

    // -----------------------------------------------------------------------
    // Groovy AST scanner
    // -----------------------------------------------------------------------

    private List<Map<String, Object>> scanGroovyAst(File file) {
        List<Map<String, Object>> entries = []
        Set<String> seen = new HashSet<String>()

        // FIX-13: reuse shared config instance (CompilationUnit is still per-call as it is stateful)
        CompilationUnit unit = new CompilationUnit(SHARED_COMPILER_CONFIG)
        unit.addSource(file)

        // We only need up to CONVERSION (builds AST) - don't do semantic analysis
        // which would require the full classpath
        unit.compile(Phases.CONVERSION)

        unit.iterator().each { SourceUnit su ->
            ModuleNode module = su.getAST()
            if (!module) return

            // Script-level methods (Groovy scripts have methods outside any class)
            module.getMethods().each { MethodNode mn ->
                if (mn.name == 'run' || mn.name == 'main') return // skip script bootstrap
                entries << methodEntry(mn, null)
            }

            module.getClasses().each { ClassNode cn ->
                // Skip the synthetic script class groovy generates
                if (cn.isScript()) return

                entries << classEntry(cn)
                String ownerName = cn.nameWithoutPackage

                // Constructors
                cn.getDeclaredConstructors().each { ConstructorNode ctor ->
                    if (!ctor.isSynthetic()) {
                        entries << ctorEntry(ctor, ownerName)
                    }
                }

                // Methods - including def methods
                cn.getMethods().each { MethodNode mn ->
                    if (mn.isSynthetic() || mn.name in ['$getStaticMetaClass']) return
                    // Skip getters/setters generated by @CompileStatic/@Canonical etc unless explicitly declared
                    if (mn.isSynthetic()) return
                    entries << methodEntry(mn, ownerName)
                }

                // Fields - include closure-valued fields (common Groovy pattern)
                cn.getFields().each { FieldNode fn ->
                    if (fn.isSynthetic()) return
                    if (fn.name in ['$staticClassInfo', 'metaClass', '__$stMC', 'METACLASS']) return
                    boolean isClosure = fn.initialValueExpression instanceof ClosureExpression
                    if (isClosure || fn.isPublic() || fn.isStatic()) {
                        entries << fieldEntry(fn, ownerName, isClosure)
                    }
                }

                // Inner classes
                cn.getInnerClasses().each { InnerClassNode icn ->
                    entries << classEntry(icn)
                }
            }
        }

        // Sort by line number
        entries.sort { Map<String, Object> a, Map<String, Object> b ->
            ((int) a.line) <=> ((int) b.line)
        }

        // Deduplicate: inner classes are visited via both the parent cn.getInnerClasses()
        // and as top-level entries in module.getClasses(), producing duplicate entries.
        List<Map<String, Object>> deduped = []
        entries.each { Map<String, Object> e ->
            String key = "${e.line}:${e.type}:${e.content}"
            if (seen.add(key)) deduped << e
        }
        return deduped
    }

    private static Map<String, Object> classEntry(ClassNode cn) {
        String kind = cn.isInterface() ? 'interface'
                    : cn.isEnum()      ? 'enum'
                    : cn.name.contains('$Trait$') ? 'trait'
                    : 'class'
        // Groovy traits show up with 'trait' modifier in the name or annotation
        if (cn.getAnnotations().any { it.classNode.nameWithoutPackage == 'Trait' }) kind = 'trait'

        int line    = cn.lineNumber    > 0 ? cn.lineNumber    : 0
        int endLine = cn.lastLineNumber > 0 ? cn.lastLineNumber : line

        return [
            line     : line,
            endLine  : endLine,
            type     : kind,
            content  : buildClassSig(cn),
            owner    : null
        ] as Map<String, Object>
    }

    private static Map<String, Object> methodEntry(MethodNode mn, String owner) {
        int line    = mn.lineNumber    > 0 ? mn.lineNumber    : 0
        int endLine = mn.lastLineNumber > 0 ? mn.lastLineNumber : line
        return [
            line    : line,
            endLine : endLine,
            type    : 'method',
            content : buildMethodSig(mn),
            owner   : owner
        ] as Map<String, Object>
    }

    private static Map<String, Object> ctorEntry(ConstructorNode cn, String owner) {
        int line    = cn.lineNumber    > 0 ? cn.lineNumber    : 0
        int endLine = cn.lastLineNumber > 0 ? cn.lastLineNumber : line
        return [
            line    : line,
            endLine : endLine,
            type    : 'ctor',
            content : buildCtorSig(cn, owner),
            owner   : owner
        ] as Map<String, Object>
    }

    private static Map<String, Object> fieldEntry(FieldNode fn, String owner, boolean isClosure) {
        int line = fn.lineNumber > 0 ? fn.lineNumber : 0
        String typeName = isClosure ? 'Closure' : fn.type.nameWithoutPackage
        String vis = fn.isPublic() ? 'public' : fn.isProtected() ? 'protected' : 'private'
        String mods = fn.isStatic() ? "${vis} static" : vis
        return [
            line    : line,
            endLine : line,
            type    : isClosure ? 'closure-field' : 'field',
            content : "${mods} ${typeName} ${fn.name}${isClosure ? ' = { ... }' : ''}".toString(),
            owner   : owner
        ] as Map<String, Object>
    }

    private static String buildClassSig(ClassNode cn) {
        int mods = cn.modifiers
        StringBuilder sb = new StringBuilder()
        if (java.lang.reflect.Modifier.isPublic(mods))    sb.append('public ')
        if (java.lang.reflect.Modifier.isAbstract(mods) && !cn.isInterface()) sb.append('abstract ')
        if (java.lang.reflect.Modifier.isFinal(mods))     sb.append('final ')
        if (cn.isInterface()) sb.append('interface ')
        else if (cn.isEnum()) sb.append('enum ')
        else                  sb.append('class ')
        sb.append(cn.nameWithoutPackage)
        ClassNode superClass = cn.superClass
        if (superClass && superClass.name != 'java.lang.Object' && superClass.name != 'groovy.lang.Script') {
            sb.append(" extends ${superClass.nameWithoutPackage}")
        }
        ClassNode[] ifaces = cn.interfaces
        if (ifaces) {
            String ifaceNames = ifaces.collect { ClassNode i -> i.nameWithoutPackage }.join(', ')
            sb.append(" implements ${ifaceNames}")
        }
        return sb.toString()
    }

    private static String buildMethodSig(MethodNode mn) {
        StringBuilder sb = new StringBuilder()
        if (mn.isPublic())       sb.append('public ')
        if (mn.isProtected())    sb.append('protected ')
        if (mn.isPrivate())      sb.append('private ')
        if (mn.isStatic())       sb.append('static ')
        if (mn.isAbstract())     sb.append('abstract ')
        if (mn.isFinal())        sb.append('final ')
        if (java.lang.reflect.Modifier.isSynchronized(mn.modifiers)) sb.append('synchronized ')
        sb.append(mn.returnType.nameWithoutPackage)
        sb.append(' ')
        sb.append(mn.name)
        sb.append('(')
        sb.append(mn.parameters.collect { "${it.type.nameWithoutPackage} ${it.name}" }.join(', '))
        sb.append(')')
        if (mn.exceptions) {
            sb.append(' throws ')
            sb.append(mn.exceptions.collect { it.nameWithoutPackage }.join(', '))
        }
        return sb.toString()
    }

    private static String buildCtorSig(ConstructorNode cn, String ownerName) {
        StringBuilder sb = new StringBuilder()
        if (cn.isPublic())    sb.append('public ')
        if (cn.isProtected()) sb.append('protected ')
        if (cn.isPrivate())   sb.append('private ')
        sb.append(ownerName)
        sb.append('(')
        sb.append(cn.parameters.collect { "${it.type.nameWithoutPackage} ${it.name}" }.join(', '))
        sb.append(')')
        return sb.toString()
    }

    // -----------------------------------------------------------------------
    // Java / fallback regex scanner  (streaming, O(n), single-pass)
    // Based on ChatGPT suggestion - handles standard Java well
    // -----------------------------------------------------------------------

    private static final Pattern CLASS_PAT = Pattern.compile(
        /^(?:\s*(?:public|protected|private|abstract|final|static|sealed|non-sealed|strictfp)\s+)*\s*(class|interface|enum|record|@interface)\s+([A-Za-z_]\w*)\b/
    )

    private static final Pattern METHOD_PAT = Pattern.compile(
        /^(?!\s*(?:if|for|while|switch|catch|do|else|try|finally)\b)\s*(?:@[\w.]+(?:\([^)]*\))?\s+)*\s*(?:public|protected|private|static|final|abstract|synchronized|native|strictfp|default|\s)*\s*(?:<[^>]+>\s+)?(?:[\w\[\]<>?.]+\s+)+([A-Za-z_]\w*)\s*\(([^)]*)\)\s*(?:throws\s+[\w.,\s]+)?\s*(?:\{|;)/
    )

    List<Map<String, Object>> scanRegex(File file) {
        List<Map<String, Object>> out = []
        String currentClass = null
        boolean inBlockComment = false
        int lineNum = 0
        // braces for endLine tracking
        int braceDepth = 0
        Deque<int[]> openStack = new ArrayDeque<>()

        file.newReader('UTF-8').withCloseable { reader ->
            reader.eachLine { String rawLine ->
                lineNum++
                String s = rawLine

                // Block comment handling
                if (inBlockComment) {
                    int end = s.indexOf('*/')
                    if (end >= 0) {
                        s = s.substring(end + 2)
                        inBlockComment = false
                    } else {
                        return
                    }
                }
                int start = s.indexOf('/*')
                if (start >= 0) {
                    int end = s.indexOf('*/', start + 2)
                    if (end >= 0) {
                        s = s.substring(0, start) + ' ' + s.substring(end + 2)
                    } else {
                        s = s.substring(0, start)
                        inBlockComment = true
                    }
                }
                int sl = s.indexOf('//')
                if (sl >= 0) s = s.substring(0, sl)
                if (!s?.trim()) return

                String trimmed = s.trim()

                // Track brace depth for endLine
                String stripped = trimmed.replaceAll(/"[^"]*"|'[^']*'/, '')
                int openB  = stripped.count('{')
                int closeB = stripped.count('}')
                if (closeB > 0) {
                    braceDepth -= closeB
                    while (!openStack.isEmpty() && openStack.peek()[1] > braceDepth) {
                        int[] top = openStack.pop()
                        if (top[0] < out.size()) {
                            out[top[0]].endLine = lineNum
                        }
                    }
                }

                // Class declarations
                def cm = CLASS_PAT.matcher(trimmed)
                if (cm.find()) {
                    String kind = cm.group(1) == '@interface' ? 'annotation' : cm.group(1)
                    currentClass = cm.group(2)
                    int idx = out.size()
                    out << mkEntry(lineNum, lineNum, kind, trimmed.take(200), null)
                    if (openB > 0) openStack.push([idx, braceDepth + openB] as int[])
                    braceDepth += openB
                    return
                }

                // Constructor
                if (currentClass && trimmed.contains("${currentClass}(")) {
                    Pattern ctorPat = Pattern.compile(
                        /^(?:\s*(?:public|protected|private)\s+)?\s*/ +
                        Pattern.quote(currentClass) +
                        /\s*\(([^)]*)\)\s*(?:throws\s+[\w.,\s]+)?\s*(?:\{|;)/
                    )
                    def k = ctorPat.matcher(trimmed)
                    if (k.find()) {
                        int idx = out.size()
                        out << mkEntry(lineNum, lineNum, 'ctor', trimmed.take(200), currentClass)
                        if (openB > 0) openStack.push([idx, braceDepth + openB] as int[])
                        braceDepth += openB
                        return
                    }
                }

                // Methods
                if (trimmed.contains('(') && trimmed.contains(')')) {
                    def mm = METHOD_PAT.matcher(trimmed)
                    if (mm.find()) {
                        int idx = out.size()
                        out << mkEntry(lineNum, lineNum, 'method', trimmed.take(200), currentClass)
                        if (openB > 0) openStack.push([idx, braceDepth + openB] as int[])
                    }
                }

                braceDepth += openB
            }
        }

        return out
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    private static Map<String, Object> mkEntry(int line, int endLine, String type, String content, String owner) {
        Map<String, Object> m = new LinkedHashMap<>()
        m.put('line', (Object) line)
        m.put('endLine', (Object) endLine)
        m.put('type', (Object) type)
        m.put('content', (Object) content)
        m.put('owner', (Object) owner)
        return m
    }

    private static String fileExt(File f) {
        String name = f.name
        int dot = name.lastIndexOf('.')
        dot >= 0 ? name.substring(dot + 1).toLowerCase() : ''
    }
}
